on:
  push:
    branches:
      - "**"
      - "!master"

name: check-job

jobs:
  check-job:
    runs-on: ubuntu-latest
    name: Pre Deploy Checks
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Run Format
        run: npm run check-format

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build
        run: npm run build
